# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e345d5590c04004af6bb62bd073319eea721658fd69d460b9b8f22424cad24210606abb12e4bc60c4ba60a8edb34d568cca7a47e4aa50951504ce89bd3efb4c1

test:
  secret_key_base: ed8dcd905ac150b07855d4e1367d9b385722d0db3dc642d487d91cdd47c82cd9a65de53a898e929817b5fba71876631ecc874925f18569ccdd8a08c5ee84f9f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
